using Common.DataAccess;
using Common.Utilities;
using ContentService.Contracts;
using Handlers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Persistence.Contexts;
using Persistence.Documents;
using Shouldly;
using Wolverine;

namespace Testing.ContentService;

/// <summary>
/// Integration tests for CreateNewRaceRequestHandler
/// </summary>
public class CreateNewRaceRequestHandlerTests : IAsyncLifetime
{
    private readonly ContentDbContext _context;
    private readonly IUnitOfWork _unitOfWork;
    private readonly CreateNewRaceRequestHandler _handler;

    public CreateNewRaceRequestHandlerTests()
    {
        var options = new DbContextOptionsBuilder<ContentDbContext>()
            .UseInMemoryDatabase($"ContentTest_{Guid.NewGuid()}")
            .Options;

        _context = new ContentDbContext(options);
        _unitOfWork = new UnitOfWork<ContentDbContext>(new TestRepositoryFactory(_context), _context);
        _handler = new CreateNewRaceRequestHandler();
    }

    public async Task InitializeAsync()
    {
        await Task.CompletedTask;
    }

    public async Task DisposeAsync()
    {
        await _context.Database.EnsureDeletedAsync();
        await _context.DisposeAsync();
    }

    [Fact]
    public async Task consume_when_valid_request_creates_race_with_generated_slug()
    {
        // Arrange
        var command = new CreateNewRaceRequest("High Elf", "Ancient magical race");

        // Act
        var result = await _handler.Consume(command, _unitOfWork);

        // Assert
        result.ShouldBeOfType<OkObjectResult>();

        var createdRace = result.ShouldBeOfType<OkObjectResult>().Value.ShouldBeOfType<RaceDocument>();
        createdRace.Name.ShouldBe("High Elf");
        createdRace.History.ShouldBe("Ancient magical race");
        createdRace.Slug.ShouldBe("high-elf"); // Slug generated by handler
        createdRace.Id.ShouldNotBeNullOrEmpty();

        // Verify saved to database
        var savedRace = _context.Races.Find(createdRace.Id);
        savedRace.ShouldNotBeNull();
        savedRace.Slug.ShouldBe("high-elf");
    }

    [Fact]
    public async Task consume_when_name_with_spaces_generates_correct_slug()
    {
        // Arrange
        var command = new CreateNewRaceRequest("Mountain Dwarf", "Skilled miners and smiths");

        // Act
        var result = await _handler.Consume(command, _unitOfWork);

        // Assert
        result.ShouldBeOfType<OkObjectResult>();
        var createdRace = result.ShouldBeOfType<OkObjectResult>().Value.ShouldBeOfType<RaceDocument>();
        createdRace.Slug.ShouldBe("mountain-dwarf");
    }

    [Fact]
    public async Task consume_when_name_with_special_characters_generates_correct_slug()
    {
        // Arrange
        var command = new CreateNewRaceRequest("Dragon-Born", "Descendants of dragons");

        // Act
        var result = await _handler.Consume(command, _unitOfWork);

        // Assert
        result.ShouldBeOfType<OkObjectResult>();
        var createdRace = result.ShouldBeOfType<OkObjectResult>().Value.ShouldBeOfType<RaceDocument>();
        createdRace.Slug.ShouldBe("dragon-born");
    }

    [Fact]
    public async Task consume_when_multiple_races_each_gets_unique_slug()
    {
        // Arrange
        var command1 = new CreateNewRaceRequest("Wood Elf", "Forest dwellers");
        var command2 = new CreateNewRaceRequest("Dark Elf", "Underground dwellers");

        // Act
        var result1 = await _handler.Consume(command1, _unitOfWork);
        var result2 = await _handler.Consume(command2, _unitOfWork);

        // Assert
        var race1 = result1.ShouldBeOfType<OkObjectResult>().Value.ShouldBeOfType<RaceDocument>();
        var race2 = result2.ShouldBeOfType<OkObjectResult>().Value.ShouldBeOfType<RaceDocument>();

        race1.Slug.ShouldBe("wood-elf");
        race2.Slug.ShouldBe("dark-elf");
        race1.Id.ShouldNotBe(race2.Id);

        // Verify both saved
        var races = _context.Races.ToList();
        races.Count.ShouldBe(2);
    }

    /// <summary>
    /// Test repository factory
    /// </summary>
    private class TestRepositoryFactory : IRepositoryFactory
    {
        private readonly ContentDbContext _context;

        public TestRepositoryFactory(ContentDbContext context)
        {
            _context = context;
        }

        public IRepository<T> CreateRepository<T>() where T : class, IDbEntity
        {
            return new TestRepository<T>(_context);
        }
    }

    /// <summary>
    /// Generic repository for testing
    /// </summary>
    private class TestRepository<T> : IRepository<T> where T : class, IDbEntity
    {
        private readonly ContentDbContext _context;
        private readonly DbSet<T> _dbSet;

        public TestRepository(ContentDbContext context)
        {
            _context = context;
            _dbSet = context.Set<T>();
        }

        public IEnumerable<T> Get(System.Linq.Expressions.Expression<Func<T, bool>>? filter = null)
        {
            return filter == null ? _dbSet.ToList() : _dbSet.Where(filter).ToList();
        }

        public IEnumerable<T> GetAll(int skip, int take)
        {
            return _dbSet.Skip(skip).Take(take).ToList();
        }

        public T? GetById(object id)
        {
            return _dbSet.Find(id);
        }

        public T? Add(T entity)
        {
            _dbSet.Add(entity);
            return entity;
        }

        public T? Delete(object id)
        {
            var entity = _dbSet.Find(id);
            if (entity != null)
            {
                _dbSet.Remove(entity);
            }
            return entity;
        }

        public T? Update(T entity)
        {
            _dbSet.Update(entity);
            return entity;
        }
    }
}
